### ISSUE TITLE
SMART FIELD RETURN OBJECT

### ISSUE THREAD

**Issue by aharon87** [ForestAdmin/forest-express-mongoose#100]
Hi, I am trying to return an object to a smart field, here is my code ;
```
 varvar  LianaLiana  ==  requirerequire(('forest-express-mongoose''forest-express );

Liana.collection('users', {
  fields: [{
    field: 'feed answer',
   type: 'Object',
    get: function (object) {
      return {1:'text',2:'texrt'};
    }
  }]
});
```

but I am getting 
<img width="761" alt="screen shot 2018-05-01 at 14 27 10" src="https://user-images.githubusercontent.com/12031960/39471421-c9b0ae4a-4d4b-11e8-890d-f839e2ddcabe.png">

**Comment by arnaudbesnier** [comment]
Hey @aharon87, `Object` is not an allowed type for Forest Smart Fields so far.
The available options are in the screenshot below:

<img width="919" alt="screen shot 2018-05-04 at 15 18 32" src="https://user-images.githubusercontent.com/664261/39630061-7f6d03a0-4fae-11e8-8e62-714fdb9c77be.png">
