### ISSUE TITLE
TypeError: Class constructor ObjectId cannot be invoked without 'new'    

### ISSUE THREAD

**Issue by thongxuan** [ForestAdmin/forest-express-mongoose#1037]
## Expected behavior

Can view collection document.

## Actual behavior

Error happens in Forest Admin.

Your server encountered an error
Please check your server logs for more information. If the error persists, please [let us know ](https://community.forestadmin.com/).

## Failure Logs

TypeError: Class constructor ObjectId cannot be invoked without 'new'    
at parseObjectId (/node_modules/forest-express-mongoose/dist/services/filters-parser.js:40:36)

## Context

* Package Version: 9.2.8
* Express Version: (koa 2.13.1, but this is not related)
* Mongoose Version: 7.0.3
* MongoDB Version: 5.2.0

**Comment by thongxuan** [comment]
Caused by:

```var ObjectId = options.Mongoose.Types.ObjectId;
    if (ObjectId.isValid(value) && ObjectId(value).toString() === value) {
      return ObjectId(value);
    }```

should be: **new** must be used to create ObjectId instance from ObjectId class:

```var ObjectId = options.Mongoose.Types.ObjectId;
     var id = **new** ObjectId(value);
    if (ObjectId.isValid(value) && id.toString() === value) {
      return id;
    }```

**Comment by jeffladiray** [comment]
Hey @thongxuan :wave:

We are currently incompatible with mongoose v7 due to a changes on mongoose types indeed.

I'll file a ticket on our issue tracker. Thanks for your feedback :pray:

**Comment by thongxuan** [comment]
Any possible workaround that you can suggest?
Thank you.

**Comment by jeffladiray** [comment]
If possible, I would suggest to rollback to mongoose 6 if possible.

Otherwise, a solution using [patch-package](https://www.npmjs.com/package/patch-package) is still possible if the fix mentionned is enough to fully handle the new type definition.
