### ISSUE TITLE
Mongoose hooks

### ISSUE THREAD

**Issue by Christilut** [ForestAdmin/forest-express-mongoose#121]
## Expected behavior

I would expect that mongoose hooks are executed, eg `pre('save', ...`

## Actual behavior

When saving a document through the forest admin interface, the document is updated in the database but hook was never executed. 

Hook does execute when I run the `save()` function in my code.

## Context

* Package Version: 2.14.2
* Express Version: 4.16.3
* Mongoose Version: 5.3.1
* MongoDB Version: 3.6.8

**Comment by Christilut** [comment]
Is this going to get fixed? This completely prevents anyone from using Forest in combination with Mongoose right now. Sure someone might not use hooks but as soon as they do, Forest falls apart.

**Comment by arnaudbesnier** [comment]
Hi @Christilut,
Thanks for the feedback, I am sorry but I cannot provide any ETA for a fix.

As a side note, I am not sure that Mongoose hooks are widely used as we have a lot of customers using Mongoose without any concern.

As the liana code is open source, it would make us very happy if you could contribute and fix it. 🤓

**Comment by FarazPatankar** [comment]
Hey @arnaudbesnier,

Any update on this issue? Also, if you guys have other issues to fix first, could you give me some pointers on how to fix this? I might pick it up myself.

**Comment by joshnissenbaum** [comment]
Really need this ASAP

**Comment by Christilut** [comment]
Not entirely. When using `findByIdAndUpdate` for example, no document is ever loaded in mongoose so no hook can be executed.
But when doing a `findOne` call and then `save` the hooks will be executed. But I guess ForestAdmin implemented it with update calls. They could change it to `save` calls but it would incur extra overhead. 

Personally I think it should like the second method because hooks not firing is not developer friendly and a surprise for anyone working with this. Especially since we have no say in what an update call actually does, the hooks were the perfect place to add extra logic.

**Comment by slimee** [comment]
Query level hooks work well with Forest.
The following snippet will work from Forest create, update and delete actions.

```
// Inside a mongoose model definition file
schema.post('save', {query:true, document:false}, function(message){
  console.log("you save a message", message)
});

schema.post('findOneAndUpdate', {query:true, document:false}, function(message){
  console.log("you update a message", message)
});

schema.post('remove', {query:true, document:false}, function(){
  console.log("you drop a message")
});
```

Please give exact information about the issues you encounter (code, UI action)

**Comment by slimee** [comment]
Solution provided in the last message.
