### ISSUE TITLE
Image Viewer distorts Image in List View

### ISSUE THREAD

**Issue by elizabethhart** [ForestAdmin/forest-express-mongoose#133]
## Expected behavior

Image Viewer displays images in List View with correct aspect ratio.

## Actual behavior

Image Viewer displays a rectangular image as a square image causing a squashed down view in List View.

Image View displays the correct aspect ratio if you click to enlarge the image or if you go into the Detail View.

## Context

* Package Version: 2.15.3
* Express Version: 4.16.2
* Mongoose Version: 4.13.7
* MongoDB Version: 2.2.30

**Comment by arnaudbesnier** [comment]
Hi @elizabethhart,

Thanks for the feedback!

Could you try to use our brand new `file viewer` widget (https://docs.forestadmin.com/documentation/reference-guide/fields/customize-your-fields/display-widgets#file-viewer) and let us know if it fixes the distortion you experienced?

Thank you.

**Comment by arnaudbesnier** [comment]
Let me close the issue.
Feel free to reopen it if the issue persists 🙏
