### ISSUE TITLE
Question : filter documents, function of Forest's connected user

### ISSUE THREAD

**Issue by Aarbel** [ForestAdmin/forest-express-mongoose#135]
Hi ForestAdmin teams.

# Now
Our sales team can manage our users with Forest. For the moment they can see / edit all of our users.

# Future
All of our sales partners will have one promo code each. Our app users will be sometimes associated with one promo code. So what we want ? As example, John is a sales partner with promo code "656Z", when he connects on our Forest Admin dashboard, we'd like that he can only manage users which are associated with the promo code "656Z".

Do you know a way to do it ?

Thanks a lot !

**Comment by arnaudbesnier** [comment]
Hi @Aarbel, this is something you should be able to do with the recent "Scopes" feature.
You'll have more information about that in the documentation:
https://docs.forestadmin.com/documentation/reference-guide/scopes#how-to-set-up-a-scope

Let me close this issue.
Feel free to re-open it if the solution does not fit your needs 🙏
