### ISSUE TITLE
Sort a populated array of references by the order of the references in the array

### ISSUE THREAD

**Issue by ozomer** [ForestAdmin/forest-express-mongoose#138]
## Expected behavior

When you have a simple has-many relationship, i.e. one parent having an array of references (i.e. object-ids) to child documents, and the relationship is populated without a specific order, you want the order of the child-documents to be in the order of the references in the array.

For example, if you have a WebPage model with an array of references to Paragraphs, the user will typically want to see the paragraphs in the order that they appear to the array.

I'm also concerned about the case of having multiple references to the same object. Should the object appear more than once in the population result? This will may not be backward compatible.

## Actual behavior

I believe that the problem resides somewhere [here](https://github.com/ForestAdmin/forest-express-mongoose/blob/devel/services/has-many-getter.js#L70-L102). You can see that the recordIds are used in the `$in` query are not passed to the next function in the promise-chain. The `$in` query does not guarantee anything about the order of the results.

## Context

* Package Version: 2.15.2
* Express Version:
* Mongoose Version:
* MongoDB Version:

**Comment by ozomer** [comment]
Any updates on this?
The issue can be fixed with a very small modification in the code: https://github.com/ForestAdmin/forest-express-mongoose/pull/139/files

**Comment by arnaudbesnier** [comment]
Fix released in v3.2.2.
Thanks for your contribution @ozomer !
