### ISSUE TITLE
How can I define a field with select box?

### ISSUE THREAD

**Issue by tan-nguyen-synova** [ForestAdmin/forest-express-mongoose#142]
I want to render fields such as gender, status as string while these fields are stored in mongoDB as Number. Ex: gender is stored in DB with value: 1 | 2 and render as  "Male" | "Female".
Thank you!

* Package Version: 
* Express Version: 4.16.3
* Mongoose Version: 5.3.6
* MongoDB Version: 4.0.5

**Comment by arnaudbesnier** [comment]
Hi @tan-nguyen-synova,

You can do that and I think the answer to your question is in the documentation.
You can decorate your fields in ForestAdmin UI with what we call widgets.

In your case you could use the `dropdown` or `Radio button`:
https://docs.forestadmin.com/documentation/reference-guide/fields/customize-your-fields/edit-widgets#dropdown 

Let me close the issue but feel free to reopen it if you cannot manage to do it with the documentation.
