### ISSUE TITLE
Edit document field submitting `null` for numeric values where existing value = 0

### ISSUE THREAD

**Issue by tannerwelsh** [ForestAdmin/forest-express-mongoose#175]
## Expected behavior

Editing a document that includes a numeric value set to `0` should not _remove_ that `0` value in the edit view, nor should it attempt to set that value to `null` when the edit form is submitted.

## Actual behavior

Starting from a document view with a numeric field set to `0`:

<img width="938" alt="Screen Shot 2019-06-07 at 1 21 25 PM" src="https://user-images.githubusercontent.com/709100/59128765-31e06f00-8928-11e9-96dc-7eefd00549e6.png">

Click on edit button, `0` value disappears from form field:

<img width="926" alt="Screen Shot 2019-06-07 at 1 25 24 PM" src="https://user-images.githubusercontent.com/709100/59128795-4886c600-8928-11e9-828f-781624c74ecd.png">

Submitting this edit form (even with no changes applied to any fields) sends the following command via Mongoose (detected with `mongoose.debug(true)`):

```
OPTIONS /forest/Segment/5cf8540c38f63f0004462c1e 204 0.172 ms - 0
(node:17272) Warning: a promise was created in a handler but was not returned from it
Mongoose: segments.findAndModify({ _id: ObjectId("5cf8540c38f63f0004462c1e") }, [], { '$set': { minimum: null } }, { new: true, runValidators: true, upsert: false, remove: false, projection: {} })
[forest] 🌳🌳🌳  Cannot update the Segment #5cf8540c38f63f0004462c1e because of an unexpected issue: MongoError: Document failed validation
Mongoose: segments.findOne({ _id: ObjectId("5cf8540c38f63f0004462c1e") }, { projection: {} })
PUT /forest/Segment/5cf8540c38f63f0004462c1e 200 10.811 ms - 566
```

**CRUCIAL PART**: why does it send `{ '$set': { minimum: null } }` ?? 

This causes the `MongoError: Document failed validation` because the Mongo validation schema includes this for the `minimum` field:

```json
      "minimum": {
        "bsonType": [
          "int",
          "double"
        ]
      },
```

## Failure Logs

See above log ^^

## Context

* Package Version: forest-express-mongoose@3.1.1
* Express Version: express@4.16.3
* Mongoose Version: mongoose@5.5.0
* MongoDB Version: v3.6.3

**Comment by Gargamel1989** [comment]
We have discovered this same issue yesterday. For now we are implementing a workaround using the pre-save hook on our model


```
modelSchema.pre('save', async function presave(next) {
  if (this.nonNullableField === null) this.nonNullableField = 0;

  return next();
}
```

**Comment by tannerwelsh** [comment]
Thanks for the tip @Gargamel1989 !

Unfortunately for us, we _do_ want this field to be "nullable", so we can't use a hook. We need to be able to trust the user input, i.e. if they submit a `$set: null`, we need to null it, and if they send a `$set: 0`, we need to set it to zero.

**Comment by arnaudbesnier** [comment]
Hi @tannerwelsh, @Gargamel1989
Thank you for the feedback, we've introduced a regression a few days ago.
I managed to reproduce the issue.

We'll patch this today for sure.

**Comment by arnaudbesnier** [comment]
The patch is now released.
Let me close the issue, feel free to reopen it if the issue persists 🙏

**Comment by tannerwelsh** [comment]
Thank you @arnaudbesnier !
