### ISSUE TITLE
ForestAdmin isn't offering any widgets for array fields

### ISSUE THREAD

**Issue by jhackett1** [ForestAdmin/forest-express-mongoose#185]
## Expected behavior

According to the documentation [here](https://docs.forestadmin.com/documentation/reference-guide/fields/customize-your-fields), the web interface should detect `Array` fields defined in the mongoose schema and offer useful widgets like checkboxes.

## Actual behavior

The fields seem to be recognised as JSON instead, with only the JSON editor widget available to edit them.

## Context

eg. for a mongoose schema like this:

```
const Snippet = new mongoose.Schema({
    title: String,
    description: String,
    href: String,
    keywords: Array
})
```

* Package Version: ^3.1.1
* Express Version: ^4.17.1
* Mongoose Version: ^5.5.14

**Comment by jhackett1** [comment]
Turned out it didn't appreciate the generic mixed array definition at `keywords: Array`. `keywords: [String]` works as expected.

Should the documentation make this explicit?

**Comment by arnaudbesnier** [comment]
Hi @jhackett1, 
We could definitely improve the documentation but It looks like the behaviour is the expected one for both `[String]` and `Array` types.

Let me close the issue. Feel free to re-open the discussion if you disagree.
