### ISSUE TITLE
Different semantics UI and mongoose

### ISSUE THREAD

**Issue by ChrisLahaye** [ForestAdmin/forest-express-mongoose#190]
## Expected behavior

When a mongoose array has `required: true` it accepts an empty array. Therefor the forest UI should also allow an empty array.

## Actual behavior

The forest UI shows a red border around array fields that are left empty.

**Comment by arnaudbesnier** [comment]
Hi @ChrisLahaye,

I think I get your point but could you share a screenshot of the input with the red borders.
I am not sure you can create an empty array with the current input which is a real issue if that's true.

Let me know and I'll create a ticket if necessary.
Thank you.

**Comment by ChrisLahaye** [comment]
@arnaudbesnier screenshot sent over Slack
