### ISSUE TITLE
When Forrest Admin UI loads, a deprecation warning is thrown

### ISSUE THREAD

**Issue by mettiu** [ForestAdmin/forest-express-mongoose#215]
## Expected behavior

I should not see deprecation warnings from mongodb driver. 

## Actual behavior

As soon as the Forest UI loads, in my nodejs server log I can see this deprecation warning:
```
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
```

## Failure Logs

```
DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use collection.countDocuments or collection.estimatedDocumentCount instead
```

## Context

*Just git clone this repo and run `yarn install` and `yarn test`: you'll see all the deprecation warnings.*

I think the problem is here:
https://github.com/ForestAdmin/forest-express-mongoose/blob/1eaf6c6f4621bcb05fc43ae3f5f56b882e0acb9d/src/services/resources-getter.js#L69

Moreover, this lib also has other deprecation warnings with Mongoose driver. See here:
https://mongoosejs.com/docs/deprecations.html

* Package Version:
* Express Version:
* Mongoose Version:
* MongoDB Version:

**Comment by arnaudbesnier** [comment]
Hey @mettiu thank you for the feedback.

**Comment by arnaudbesnier** [comment]
It will be fixed with this PR: https://github.com/ForestAdmin/forest-express-mongoose/pull/216
And the patch will probably be applied in v4.0.0.

**Comment by mettiu** [comment]
> Hey @mettiu thank you for the feedback.

No problem. Happy to help.
Looking forward to get the next release.
