### ISSUE TITLE
Cannot load users/customers collection when Intercom integration is enabled

### ISSUE THREAD

**Issue by ahmadassaf** [ForestAdmin/forest-express-mongoose#243]
## Expected behavior

I expect that I am able to load the data for the users/customers collection if I have an Intercom integration enabled

## Actual behavior

I expect to be able to load the data for those collections and then when drilling down into a specific user to be able to see the data coming from Intercom
```

## Failure Logs

```bash
[forest] 🌳🌳🌳  Unexpected error: Cannot read property 'collection' of undefined
TypeError: Cannot read property 'collection' of undefined
    at QueryBuilder.addJoinToQuery (/.../node_modules/forest-express-mongoose/dist/services/query-builder.js:44:26)
```

## Context

* Express Version: 4.16.3
* Mongoose Version: ~5.3.6
* MongoDB Version: 4.0.3

## Notes

I was able to circumvent the issue by doing:

```js
      if (!!subModel) {        
        joinQuery.push({
          $lookup: {
            from: subModel.collection.name,
            localField: field.field,
            foreignField: referencedKey,
            as: field.field
          }
        });
      }
```

As the error on https://github.com/ForestAdmin/forest-express-mongoose/blob/devel/src/services/query-builder.js#L21 was giving that `subModel` is not defined.

I am not sure about the side effects of this but if thats the case I am happy to open a PR.

Thanks

**Comment by louisteenbrink** [comment]
Hey, @ahmadassaf thank you for letting us know.

We've recently released a new version that should fix your issue - https://github.com/ForestAdmin/forest-express-mongoose/blob/devel/CHANGELOG.md#release-404---2019-10-15

I hope that helps!

cc @arnaudbesnier

**Comment by arnaudbesnier** [comment]
Let's close this issue.
@ahmadassaf if the upgrade to v4.0.4 does not fix the issue, feel free to re-open this ticket.

🌲🌲🌲
