### ISSUE TITLE
[*] Charts - Data filters not applied

### ISSUE THREAD

**Issue by JoepDriesen** [ForestAdmin/forest-express-mongoose#248]
## Expected behavior

When applying filters in charts in the dashboard or when searching for data in the Data tab, the data is correcty filtered

## Actual behavior

The filters are not being applied and instead all data is shown

## Failure Logs

No error logs found in console

![Capture](https://user-images.githubusercontent.com/12200799/66997610-16a21f00-f0d3-11e9-93c0-f06c55c622ff.PNG)

## Context

TODO: Please provide any relevant information about your setup.

* Package Version: 4.0.3
* Express Version: 4.16.4
* Mongoose Version: 5.3.14
* MongoDB Version: 3.6

**Comment by arnaudbesnier** [comment]
Hi @JoepDriesen,
Thanks for your feedback.

I cannot reproduce so far with the same kind of filter conditions.
<img width="1680" alt="Screenshot 2019-10-28 at 08 22 33" src="https://user-images.githubusercontent.com/664261/67659267-43202b80-f95c-11e9-8873-33d686b8b19b.png">

Could share with us the logs of your server for the broken charts to see if those conditions are well transmitted and if the query looks good?

**Comment by JoepDriesen** [comment]
Hi,

Thanks for responding. We have downgraded our forest liana package to 3.x for the past few months, so didn't really look into this issue anymore. However, we would like this resolved now because of the new features and bugfixes :).

I have upgraded our QA environment again to "forest-express-mongoose": "^5.4.0"

The issue is only happening in our Azure environment. Local development environment seems to apply the filters correctly.

Also, this is not only an issue with the dashboard charts. It is the same issue anywhere filters are applied (i.e. when searching records with filters in the Data tab).

I have inspected the mongoDB log, and it appears the filters are not being sent correctly to mongodb:

This is a log record from mongodb after I search our "Result" collection with a filter:

`
{
        "op" : "query",
        "ns" : "buffl-qa.results",
        "command" : {
                "find" : "results",
                "filter" : {                },
                "projection" : {                },
                "limit" : 10,
                "returnKey" : false,
                "showRecordId" : false,
                "lsid" : {
                        "id" : UUID("73636803-b62a-475f-ac0e-ed253c375079")
                },
                "$db" : "buffl-qa"
        },
        "keysExamined" : 0,
        ...
   }
`

As you can see, the filter is empty. The server log show the filter arrives correctly to the forest endpoint:

`2019-12-03T10:45:52.414051658Z ::ffff:172.16.1.1 - - [03/Dec/2019:10:45:52 +0000] "GET /forest/Result/count?fields%5BResult%5D=_id%2Ccampaign%2Cuser%2Ccomplete%2Cdeleted%2CcreatedAt%2Ccustom_client_identifier&fields%5Bcampaign%5D=name&fields%5Buser%5D=email&filters=%7B%22field%22%3A%22campaign%3Alanguage%22%2C%22operator%22%3A%22equal%22%2C%22value%22%3A%22Dutch%22%7D&searchExtended=0&timezone=%2B01%3A00 HTTP/1.1" 304 - "https://app.forestadmin.com/34771/data/1379457/index?filterType=and&campaign:language[0][val]=Dutch&campaign:language[0][op]=is" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"`

So as far as I can tell, something must be going wrong in the forest liana... I'm not sure where to look next. Any suggestions?

Thanks!

**Comment by JoepDriesen** [comment]
Hi,

We have resolved this issue.

Somehow a stale node_modules folder was present in our build directory on the azure server. This seemed to cause forest to use these outdated packages somehow.

After deleting this folder, everything works as expected.
