### ISSUE TITLE
Once again impossible to use forest-express-mongoose in ES5 environment

### ISSUE THREAD

**Issue by kevin-frugier** [ForestAdmin/forest-express-mongoose#27]
This is not per-se your fault but this shows why it's dangerous to use "fuzzy" npm package versions when it comes to using NodeJS in PRODUCTION.

forest-express-mongoose 2.2.25 depends on forest-express "^0.1.33" which currently resolves to 0.1.33
forest-express 0.1.33 depends on jsonwebtoken "^7.1.9" which currently resolves to 7.2.0
jsonwebtoken 7.2.0 depends on joi ^10.0.1 which currently resolves to 10.0.5
joi 10.0.5 breaks on ES5 because of :
`const Hoek = require('hoek');` https://github.com/hapijs/joi/blob/master/lib/index.js#L5

All that because of stupid merge request in jsonwebtoken which warns them of failure on old node env : 
https://travis-ci.org/auth0/node-jsonwebtoken/builds/179471404

Linking forest explicitly to jsonwebtoken version 7.1.9 will fix this until they fix their mistake.

Until then, we are back to square one being unable to use forest with ES5.

Edit : here is my comment for the jsonwebtoken team https://github.com/auth0/node-jsonwebtoken/commit/99127eeb53a6d316ce94482cfa03d006346bd1ef#commitcomment-20103622

**Comment by kevin-frugier** [comment]
@jfromaniello has been uber-reactive and has fixed the issue for jsonwebtoken : https://github.com/auth0/node-jsonwebtoken/commit/8da893ae31e0266cb9277c4b931f79375841e545

However you might want to consider stricter rules in forest-express regarding dependencies. Your call.

**Comment by arnaudbesnier** [comment]
@kevin-frugier thanks for the report.
Having strict rules for our NPM packages is definitely something we have in mind.

**Comment by SeyZ** [comment]
Using https://docs.npmjs.com/cli/shrinkwrap ?
