### ISSUE TITLE
[forest] 🌳🌳🌳  Cannot customize your collection named "users" properly.

### ISSUE THREAD

**Issue by GautierT** [ForestAdmin/forest-express-mongoose#33]
Hi,
I add 
```
app.use(require('forest-express-mongoose').init({
    modelsDir: __dirname + '/models',  // Your models directory.
    envSecret: config.forest.env_secret,
    authSecret: config.forest.auth_secret,
    mongoose: mongoose // The database connection.
}));
```
before my app.listen. And i can see the data in Forest so thats seems okay.

But when i add a file in forest/users.js with 
```
var Liana = require('forest-express-mongoose');
Liana.collection('users', {
    actions: [{ name: 'Ban user' }]
});
```
nothing append. And if i require that file (despite the fact that it's not advised)  i can see : 
`[forest] 🌳🌳🌳  Cannot customize your collection named "users" properly. Did you call the "collection" method in the /forest directory?`

What should i do ?
Thanks

**Comment by SeyZ** [comment]
Hey @GautierT 

Thanks for your issue! Can you check if your collection name (not your mongoose model name) is `users`?

You're right, you don't have to require the file manually.

**Comment by arnaudbesnier** [comment]
@GautierT any news on this issue?
Did you eventually manage to customize your `users` collection?

**Comment by GautierT** [comment]
Yes but with a workaround thanks to a skype with @SeyZ.
The problem was the same that in this issue : https://github.com/ForestAdmin/forest-express/issues/6
And i still can't put my admin to production because of this.

**Comment by arnaudbesnier** [comment]
The feature is now in code review and will be released soon.

**Comment by arnaudbesnier** [comment]
The new option will be: 
```
app.use(require('forest-express-mongoose').init({
    modelsDir: __dirname + '/models',  // Your models directory.
    smartDir: __dirname + '/my/forest/custom/directory',  // Your Forest Smart implementation directory.
    envSecret: config.forest.env_secret,
    authSecret: config.forest.auth_secret,
    mongoose: mongoose // The database connection.
}));
```
