### ISSUE TITLE
[SmartActions] Is there a way to set a custom URL to POST to for an action?

### ISSUE THREAD

**Issue by NickMihaiu91** [ForestAdmin/forest-express-mongoose#34]
Hello,

From what I've seen here [http://doc.forestadmin.com/developers-guide/#creating-an-action](http://doc.forestadmin.com/developers-guide/#creating-an-action) and in trying to create a smart action Forest expects the URL for a smart action to be smth like: /forest/actions/action-name 

Is there any way you can set a custom URL for the API when you define the smart action? Smth like this:

```
var Liana = require('forest-express-mongoose');

Liana.collection('customers', {
  actions: [{ name: 'Ban user', url: '/your-custom-url' }]
});
```

Thank you!

**Comment by SeyZ** [comment]
Hey @NickMihaiu91 you can use the parameter `endpoint` instead of `url`. Thanks for asking! We should definitely document this.

Feel free to reopen this issue if it does not work,
thanks!
