### ISSUE TITLE
TypeError: RecordsRemover is not a constructor

### ISSUE THREAD

**Issue by Emixam23** [ForestAdmin/forest-express-mongoose#356]
## Expected behavior

Should remove multiple records: https://docs.forestadmin.com/documentation/v/v6/reference-guide/routes/default-routes#delete-a-list-of-records

## Actual behavior

From the code stated in the above documentation link, I get `TypeError: RecordsRemover is not a constructor`

```
// Delete a list of outfits
router.delete('/outfitProductsCollection', permissionMiddlewareCreator.delete(), (request, response, next) => {
  // Learn what this route does here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/routes/default-routes#delete-a-list-of-records
  new RecordsGetter(outfitProductsCollection).getIdsFromRequest(request)
  .then((ids) => {
    const recordsRemover = new RecordsRemover(ids);
    recordsRemover.perform(request)
      .then(() => response.status(204).send())
      .catch(next);
  })
  .catch(next);
});
```

## Failure Logs

[start] DELETE /forest/outfitProductsCollection 500 283 - 12.286 ms
[start] TypeError: RecordsRemover is not a constructor
    at /Users/emixam23/Workspace/forest-admin/eyesapp/routes/outfit-products-collection.js:71:28

## Context

I am using the latest version of ForestAdmin (setup from the website using Docker)

**Comment by rap2hpoutre** [comment]
Hi @Emixam23,

There was an error on our documentation about `RecordsRemover` that has been fixed a few days ago. You could have a look here for more information: https://community.forestadmin.com/t/typeerror-recordsremover-is-not-a-constructor-forest-admin-mongoose/489/9?u=rap2h

Let me know if it fixes your issue!

**Comment by Emixam23** [comment]
Hey @rap2hpoutre 

Yes I know, I am behing Thomas Anderson ^^ We just don't have github account that's why I used my personal one

Thanks

**Comment by rap2hpoutre** [comment]
> Yes I know, "I am" Thomas Anderson ^^

Oops 🤣 

OK, so I close this issue if you don't mind!
