### ISSUE TITLE
Is modelsDir option needed?

### ISSUE THREAD

**Issue by vshulev** [ForestAdmin/forest-express-mongoose#43]
I noticed that there is no mention of `modelsDir` when I search the source code of the project. I am also seeing that there is a `getModels` function which actually gets the models from `mongoose.models`. So is `modelsDir` actually a required configuration option?

I am asking because our models are enclosed in functions like:
```
module.exports = function (app) {
    return new Schema({ ... })
}
```
and so we can't really pass a models folder to `forest-express-mongoose` without some build step first.

**Comment by arnaudbesnier** [comment]
hi @vshulev, `modelsDir` is not a mandatory option. You're right, it is not explained anywhere in the documentation or during the onboarding steps.

Depending of your app implementation you will need it or not. If your models have already been required, before the liana integration call then it is not a necessary option.

Have fun using Forest!
🌲🌲🌲

**Comment by Christilut** [comment]
I'm using https://www.npmjs.com/package/@decorators/mongoose for my models and the modelsDir didn't work for that so I thought I was stuck until I saw this issue. 
If modelsDir is optional, that should really be documented somewhere (preferably in the onboarding).

**Comment by arnaudbesnier** [comment]
Hey @Christilut, I agree this should be documented.
But if you have an issue with `modelsDir` usage, this might be a bug, so feel free to create an issue on Github in this repo.

**Comment by Christilut** [comment]
Well I'm using the above decorators so I wasn't excepting forest to work out of the box with them. So I don't think that's a bug. I'm already glad to see that forest works with `mongoose.models`.
