### ISSUE TITLE
Edit form for subdocuments not displaying properly

### ISSUE THREAD

**Issue by vshulev** [ForestAdmin/forest-express-mongoose#44]
Hi,

I believe there are a couple of bugs when adding a new subdocument in the Forest Admin app.

Firstly, enums correctly display as drop-downs when adding the main document, but in the subdocument there are no inputs at all. Here's an example of a regular string field and two enums it a subdocument:
<img width="591" alt="capture" src="https://cloud.githubusercontent.com/assets/5750234/23314799/45c83386-fa78-11e6-9562-7eea621a02bf.PNG">

The other issue is again related to sudocuments. Auto-generated input fields such as `id` and `created_at`, `updated_at` are not disabled.

**Comment by arnaudbesnier** [comment]
Hi @vshulev you're right, subdocuments do not support enums properly.
I made the enhancement. The fix should be released the coming week.
I'll let you know.

Thanks for the report.

**Comment by laruche** [comment]
Hello 
I still found same error on my subdocuments (include in Array) 

`
content : {
      type: [
        {
          locale : {
            type : String,
            enum : ['FR_FR', 'AR_AR'],
            required : true,
            default : 'FR_FR'
          }
        }
     ]
}
`
![capture d ecran 2018-10-01 a 17 37 19](https://user-images.githubusercontent.com/1287795/46302331-ae080300-c5a0-11e8-8b74-65b2a4122f90.jpg)

**Comment by arnaudbesnier** [comment]
Hi @lauche you're in the context of an array of subdocuments (vs a single subdocument here).
