### ISSUE TITLE
How about having a rich text editor for a filed.

### ISSUE THREAD

**Issue by ItsMrAkhil** [ForestAdmin/forest-express-mongoose#56]
I am wondering is it possible to add a rich text editor like QuillJS for a specific field as like we can show image in place a field?

**Comment by arnaudbesnier** [comment]
Hi @ItsMrAkhil, you have a "Rich Text Editor" widget you can setup on "String" type fields.

In the Admin,
- go in your collections setting > fields
- select the field you want to configure
-  add the "rich text editor" widget.

But this widget is not based on QuillJS.
