### ISSUE TITLE
Validation is not being enforced

### ISSUE THREAD

**Issue by gunar** [ForestAdmin/forest-express-mongoose#57]
Hi, is there a way to make sure ForestAdmin adheres to my models' custom validators?

I thought this should work out-of-the-box since this is a mongoose plugin, not just mongo.

For example, I have a validation that makes sure codes are unique across three collections.

Thank you for ForestAdmin. Love it!
Don't know how nobody thought of it before.

**Comment by arnaudbesnier** [comment]
Hi @gunar, validation is not something the current liana manage properly.
We definitely want to improve this, in the future releases.

As you may notice, we have a PR in review to support simple validations here: https://github.com/ForestAdmin/forest-express-mongoose/pull/35

But you seem to have complex validations. We would love to have a small example of your complex validation to help us implement it.

🌲🌲🌲

**Comment by gunar** [comment]
Hi @arnaudbesnier 
Thanks for the quick response

Why it is needed to implement code for validation?
If you take my model and do `instance.save()` it will throw, in case of validation errors
Isn't that what `forest-express-mongoose` does?

**Comment by arnaudbesnier** [comment]
@gunar sorry for the misunderstanding... The PR I showed you is a feature to improve the validation experience.

You are right, as the liana is based on the Mongoose ORM. It means that the validations you defined in your models should work while using Forest.
If I understand well, you are submitting an issue here, right?
Your custom validations are simply not executed or do you notice another unexpected behaviour?

Can you provide a simple code example based on your code, that we could use to reproduce the issue?

**Comment by gunar** [comment]
Thank you for the feedback
Here's the code https://github.com/gunar/forestRepro
Validators are not being checked on updates (only on inserts, it seems)

### Validator on insert works
Create
    bitcoin.code = 'ZZZ'
Then try to create
    litecoin.code = 'ZZZ'
I get a validation error

### Validator on update does not work
Create
    bitcoin.code = 'ZZZ'
    litecoin.code = 'ZZA'
Then update
    litecoin.code = 'ZZZ'
I get no validation error, but should have

**Comment by arnaudbesnier** [comment]
@gunar Ok I think I found the reason why the validations are not triggered on record update. I think the method `findByIdAndUpdate` (https://github.com/ForestAdmin/forest-express-mongoose/blob/devel/services/resource-updater.js#L19) needs to have the `runValidators` option set to `true` which is not the case.

Let me reproduce and fix this week.

**Comment by arnaudbesnier** [comment]
@gunar can you check if the PR fixes your issue?

**Comment by arnaudbesnier** [comment]
The fix has been release in the 1.1.5 liana version. Here are the [changelogs](https://github.com/ForestAdmin/forest-express-mongoose/blob/devel/CHANGELOG.md#release-115---2017-05-30).
