### ISSUE TITLE
Smart relationship does not query the route

### ISSUE THREAD

**Issue by RobinHerzog** [ForestAdmin/forest-express-mongoose#626]
## Expected behavior

I'm looking to display related data thanks to smart relationship.
Field is created and displayed on UI.

UI should display my data related to the other data

## Actual behavior

FA does not call the specific route `/organers/:organizer_id/relationships/events` 
No error

```
  "dependencies": {
    "body-parser": "1.19.0",
    "chalk": "~1.1.3",
    "cookie-parser": "1.4.4",
    "cors": "2.8.5",
    "debug": "~4.0.1",
    "dotenv": "~6.1.0",
    "express": "~4.17.1",
    "express-jwt": "5.3.1",
    "forest-express-mongoose": "^7.8.4",
    "mongoose": "^5.13.2",
    "morgan": "1.9.1",
    "require-all": "^3.0.0"
  },
```

**Comment by CameronLayUp** [comment]
Hi @RobinHerzog, were you able to fix this? I'm having the same issue.

**Comment by RobinHerzog** [comment]
No I could not fix it yet

**Comment by CameronLayUp** [comment]
I can confirm that this broke after v7.8.4. It works as it should in v7.8.3 but is broken in any version after it, even v8

**Comment by t1bb4r** [comment]
I think it might have been fixed here, https://github.com/ForestAdmin/forest-express-mongoose/pull/639/files, tagged v8.0.1
