### ISSUE TITLE
Smart actions - primaryKeys not generated in forestadmin schema

### ISSUE THREAD

**Issue by kvnsw** [ForestAdmin/forest-express-mongoose#637]
## Actual behavior

Smart actions do not seem to work because of primaryKeys array not being generated for Schemas within the .forestadmin-schema.json file.

As a result, an error is thrown while using the `permissionMiddlewareCreator` middleware within Smart Actions https://github.com/ForestAdmin/forest-express/blob/5816ee2d81129233df1a341cdc40c76e4e516493/src/middlewares/permissions.js#L117

(`primaryKeys.length` throws an error as `primaryKeys` is undefined)

## Context

* Package Version: 8.0.0
* Express Version: 4.17.1
* Mongoose Version: 5.13.3

**Comment by arnaudbesnier** [comment]
Hi @kvnsw, the team will release a patch soon.
Thanks for your patience.

**Comment by romain-gilliotte** [comment]
Fixed in https://github.com/ForestAdmin/forest-express-mongoose/commit/80491d40c679c87d2fd4162acfd34fa904381d6b
