### ISSUE TITLE
Field Names - Field names beginning with an underscore break the list view

### ISSUE THREAD

**Issue by f19yd** [ForestAdmin/forest-express-mongoose#64]
Impossible to query list of my users. Something strange with sub-keys of model

[forest] 🌳🌳🌳 Unexpected error in the list view:

### My model

```javascript
const UserSchema = new Schema({
  email    : { type: String, required: true, lowercase: true },
  locale   : String,
  ...

  _facebook: {
    id        : String,
    name      : String,
    first_name: String,
    last_name : String
  },
  ...

});

module.exports = UserSchema;
```

### Output error
Error message : "No model was found for 'forest-users-facebook'"

**Comment by arnaudbesnier** [comment]
Hi @f19yd, It is a Forest bug probably due to the underscore in `_facebook` key. Not sure we'll fix this quickly.
A workaround would be to reformat the key to be `facebook`.

**Comment by arnaudbesnier** [comment]
Hi @f19yd,

We've made some improvements to be more permissive about collections and fields names.
Can you try to upgrade to the latest package version and see if it fixed your issue?

Thanks you!

**Comment by arnaudbesnier** [comment]
@f19yd,
I tried to reproduce on one of my projects, adding this to one of my schemas:
``` javascript
_facebook: {
    id        : String,
    name      : String,
    first_name: String,
    last_name : String
  },
```

It works fine with the latest liana version.
Let me know if you need more help.

🎄🎄🎄
