### ISSUE TITLE
Having trouble connecting

### ISSUE THREAD

**Issue by mhjb** [ForestAdmin/forest-express-mongoose#667]
I'm sorry for the likely amateur error (I don't have deep express experience), but I'm having trouble installing forest-express-mongoose into my express app. 

In my app.js I have:

```  
const forest = require('forest-express-mongoose');
const mongoose = require('mongoose');

...

app.db
  .connect()
  .then(async () => {
    app.use(await forest.init({
      envSecret: config.forest.FOREST_ENV_SECRET,
      authSecret: config.forest.FOREST_AUTH_SECRET,
      objectMapping: mongoose,
      connections: { default: app.db.connection },
    }));
  })
```

And forest appears to initialise, but any requests from app.forestadmin.com to forest routes, e.g. `OPTIONS /forest/authentication` fail, and there aren't any forest routes if I have a look at `app._router.stack`.

Any hot tips?

**Comment by arnaudbesnier** [comment]
Hi @mhjb !
Can you re-share your installation issue in our [community forum](https://community.forestadmin.com/) 🙏 ?
The team tend to respond to new topics in less than 24h there. 👍

**Comment by mhjb** [comment]
I was helped by Forest Admin support. 

The trouble was I had a catch-all route intended to handle errors that I didn't notice was being set up before the Forest middleware is initialised, because the latter has to wait for the Mongoose connection.
