### ISSUE TITLE
Admin interface does not show value 0 for Number field on nested objects

### ISSUE THREAD

**Issue by levynir** [ForestAdmin/forest-express-mongoose#69]
Steps to reproduce:
1. Create a model like this:
```
module.exports.Example = mongoose.model('Example', new mongoose.Schema({
    title:      { type: String, },
    type:       { type: String, enum: ['buttons','select','form']},
    buttons:    [{
        title: String,
        value: Number
    }],
    fields:     [{
        title: String,
        ftype: { type: String, enum: ['select', 'input']},
        values: { type: Array },
    }]
}));
```

2. Go to Forest Admin
3. Add a new Example
4. Add two buttons
5. Button 1: title=Yes, Value=100
6. Button 2: title=No, Value=0
7. Save Example object
8. Button 2 does not show the value in the admin interface

**Comment by arnaudbesnier** [comment]
hey @levynir, thanks for the report!

We will fix this before the end of the week.
I'll let you know.

🌲🌲🌲

**Comment by lucasscariot** [comment]
Hello @levynir, we have just deployed a fix for this behaviour. No liana update required, only our client application was concerned 🙂
