### ISSUE TITLE
Support nested custom schemas for models

### ISSUE THREAD

**Issue by mcaldas** [ForestAdmin/forest-express-mongoose#76]
Hi,
Is there a chance you can add support for custom schemas inside a model?
For example, lets say i have a `user` model, and on of its fields is a custom schema, lets say 
```
var subscriptionSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['type1', 'type2', 'type3'],
  },
  data: mongoose.Schema.Types.Mixed,
  expires_at: Date
});
```
And in the user schema we have among others:

```
userSchema = new mongoose.Schema({
    subscription: subscriptionSchema
});
```

Right now there is no way to handle or visualize those in the admin panel, they just appear as objects.

**Comment by arnaudbesnier** [comment]
@mcaldas Thanks for the feedback!

We definitely need to work on this.
We might plan it for the next sprint.

**Comment by mcaldas** [comment]
@arnaudbesnier great! 
When is your next sprint?  :)

**Comment by arnaudbesnier** [comment]
Next week ;)

**Comment by mcaldas** [comment]
Great!

**Comment by arnaudbesnier** [comment]
The support is available on the latest liana version 1.2.3.

Thanks again!
Let us know if it does not work as expected.

🌲🌲🌲

**Comment by mcaldas** [comment]
@arnaudbesnier seems to be working thank you!
I realized that composite mongoose types aren't serialized either, for example `mongoose.Schema.Types.Point`
Is that a different issue?

**Comment by mcaldas** [comment]
@arnaudbesnier  another issue is that on list view i see something like `<client@model:forest-users-someschema::ember5328:owner(XXXXXXXX)>`
Is that the expected behavior?

**Comment by arnaudbesnier** [comment]
@mcaldas, you are right on both points. Can you create an issue for each comment?
We'll try to prioritise the fixes for next week.

**Comment by mcaldas** [comment]
Sure will do

**Comment by mcaldas** [comment]
@arnaudbesnier just created the 2 issues: #78 #79

**Comment by aharon87** [comment]
Hi,
For me, it's doesn't work.
When I turn the field to mongoose.Schema.Types.Mixed the field in forest admin is disappear.
