### ISSUE TITLE
Meta `count` not working on Serializer

### ISSUE THREAD

**Issue by GautierT** [ForestAdmin/forest-express-mongoose#81]
Hi,
Following this tutorial : https://doc.forestadmin.com/developer-guide/express-mongoose.html#example-hasmany-smart-relationship

The count params don't work. 

For : 
```
const serialized = await new Serializer(Liana, Letters, results.docs, {}, {
     count: results.total
    // Don't seem to work
}).perform()
debug('serialized : %O', serialized)
```

I don't see the `{ meta : { count : NUMBER } }`

Temporary fix to have pagination working: 

`return res.send({...serialized, meta : {count : results.total}})`

**Comment by arnaudbesnier** [comment]
@GautierT, are you sure that `result.total` contains the total number of records?

If the answer is yes, I see that in the documentation, the `length` of records is used. Are you sure that your `results.total` returns an integer value?

**Comment by GautierT** [comment]
Yes,  i'm sure. I'm using : https://github.com/edwardhotchkiss/mongoose-paginate
And as you can see in my temporary fix if i manually pass `meta : {count : results.total}` pagination is working.

**Comment by arnaudbesnier** [comment]
Yes, can you answer my second question? Is `results.total` an integer value?
What happens if you set an hardcoded value?

**Comment by GautierT** [comment]
Sorry missed that one. Yes, it's an integer value.
I tried with `count : 40`. Does'n't work.

**Comment by arnaudbesnier** [comment]
@GautierT, Ok, I got it! Thank you for the feedback.
The `Serializer` implementation might have change recently.

Can you try with this implementation:
```javascript
const serialized = await new Serializer(Liana, Letters, results.docs, null, {}, {
     count: results.total
    // Don't seem to work
}).perform()
debug('serialized : %O', serialized)
```

**Comment by GautierT** [comment]
Yes, it's working. Thanks.

**Comment by arnaudbesnier** [comment]
We'll update the documentation soon on this issue.

Thanks @GautierT 

🌲🌲🌲

**Comment by SeyZ** [comment]
FYI, the doc is now updated ;)
