### ISSUE TITLE
Validation fails for array fields when value have leading whitespace

### ISSUE THREAD

**Issue by levynir** [ForestAdmin/forest-express-mongoose#85]
(posting this here but it might be related to forest-express in general)
Steps to reproduce:
```
const UserSchema = new mongoose.Schema({
    type:           { type: String, enum: ['New Lead', 'Lead', 'User' ,'Customer']},
    ....
    problem:        [ { type: String, enum: ['Value1', 'Value2', 'Value3',]}],
});
module.exports = mongoose.model('User', UserSchema );
```

Edit `Problem` field in the UI. Set value to `Value1,Value2` (no space after the ,) and save.
Value is loaded to the screen as `Value1, Value2` (with whitespace). Change `Value2` to `Value3` (keep the whitespace) and save.

You get an error message 
```
Validation failed: problem.1: ` Value3` is not a valid enum value for path `problem`.
```
Expected: either allow save with leading whitespace or make sure data is loaded top screen without whitespace.

**Comment by arnaudbesnier** [comment]
Hi @levynir,
Thanks for the feedback.

We didn't really implemented the support of Arrays of Enums yet. I am not surprised it does not work properly right now.
We should also have a better experience than a simple input for such fields (like a multi-select widget).

Not sure we'll be able to improve this in the following weeks, but we'll let you know.

**Comment by arnaudbesnier** [comment]
Hi @levynir, the fix will be released tomorrow morning.
You won't need to upgrade the liana as it was a "client" issue.

Thanks!

🎄🎄🎄
