### ISSUE TITLE
forest UI display wrong enum when using same-name subfields

### ISSUE THREAD

**Issue by levynir** [ForestAdmin/forest-express-mongoose#89]
## Expected behavior

assume a model like this:
```
const UserSchema = new mongoose.Schema({
    type:           { type: String, enum: ['New Lead', 'Lead', 'User']},
    name: {
        first:      { type: String, trim: true, },
        last:       { type: String, trim: true, },
    },
    comment:        { type: String, trim: true },
    email:          { type: String, trim: true, },
    weight: {
        value:      { type: Number, min: 30,  validate: Number.isInteger},
        unit:       { type: String, enum: ['kgs', 'lbs']}
    },
    height: {
        value:      { type: Number,  validate: Number.isInteger },
        unit:       { type: String, enum: ['cm', 'in'] }
    },
....

```
in the forest admin UI it is expected that the `unit` field for `height` would show a dropdown with 'cm' and 'in'

## Actual 

the dropdown display 'kgs' and 'lbs'
![screen shot 2017-11-26 at 15 19 58](https://user-images.githubusercontent.com/5058191/33240354-7c3c58ac-d2bd-11e7-80a9-8b5afb05f7a5.png)

## Details
* Package Version:     "forest-express-mongoose": "^1.4.9",
* Express Version:    "express": "^4.15.4",
* Mongoose Version:    "mongoose": "^4.11.9",
* MongoDB Version:  db version v3.4.9 git version: 876ebee8c7dd0e2d992f36a848ff4dc50ee6603e

**Comment by levynir** [comment]
ping

**Comment by arnaudbesnier** [comment]
Hey @levynir, I'll try to reproduce this issue and fix it this evening.

**Comment by arnaudbesnier** [comment]
Hi @levynir, the fix will be released tomorrow morning.
You won't need to upgrade the liana as it was a "client" issue.

Thanks!

🎄🎄🎄

**Comment by levynir** [comment]
Confirmed fixed. Thanks Arnaud!
