### ISSUE TITLE
Feature request : provide generic Node.js / Mongoose config for Forest 

### ISSUE THREAD

**Issue by Aarbel** [ForestAdmin/forest-express-mongoose#90]
Hi guys, could you create a generic Node.js / Mongoose config for Forest ?
We use KOA, so your installation sets are not compatible.

Thanks !

Clement from Paris

**Comment by arnaudbesnier** [comment]
Hi @Aarbel, we would love to work on this kind of liana but we're still a small technical team.

I think you have 3 solutions if you want to use Forest on your project:

- Instantiate an Express app dedicated to Forest, on which you could initialise Forest with your Mongoose models. It seems to be the fastest solution.
- Create a Pull Request on this repo, to ask for the creation of the Express app on Forest initialisation.
- Implement a dedicated liana Node.js/Mongoose.

I really prefer the first one :)

**Comment by Aarbel** [comment]
Hi Arnaud, thanks for your quick message !  

For the second point you mean 'Koa app' instead of 'Express app' isn't it ?

Choosing Framework compatibility (and not Langage !) could be a consistent brake for your Tech UX and development... ;) (right now i'm looking for other solutions). Creating a specific instance for Forest with duplicated models of our api is very ugly for maintance... or a lot of time with docker config !

**Comment by Aarbel** [comment]
@SeyZ @arnaudbesnier 

Hi guys ! Congrats for your Funding Round ;) So what are your next steps to make Forest easier to install for Koa and other node.js libraries ? :)

**Comment by Aarbel** [comment]
@SeyZ @arnaudbesnier any news about it :)

**Comment by root-io** [comment]
Hey @Aarbel I wanted to use Koa as well, @ArnaudValensi pointed me out the `koa-connect` repo.

I was able to connect Forest following those steps:

```shell
$ npm install --save https://github.com/cyrilluce/koa2-connect
```

```javascript
const c2k = require('koa-connect')

app.use(c2k(require('forest-express-mongoose').init({
  modelsDir: __dirname + '/models', // Your models directory.
  envSecret: process.env.FOREST_ENV_SECRET,
  authSecret: process.env.FOREST_AUTH_SECRET,
  mongoose: require('mongoose') // The mongoose database connection.
})))
```

**Comment by ChrisLahaye** [comment]
> Hey @Aarbel I wanted to use Koa as well, @ArnaudValensi pointed me out the `koa-connect` repo.
> 
> I was able to connect Forest following those steps:
> 
> ```shell
> $ npm install --save https://github.com/cyrilluce/koa2-connect
> ```
> 
> ```js
> const c2k = require('koa-connect')
> 
> app.use(c2k(require('forest-express-mongoose').init({
>   modelsDir: __dirname + '/models', // Your models directory.
>   envSecret: process.env.FOREST_ENV_SECRET,
>   authSecret: process.env.FOREST_AUTH_SECRET,
>   mongoose: require('mongoose') // The mongoose database connection.
> })))
> ```

It seems like the data is being loaded but I can't get passed the `Unlock your data` screen. `POST /forest/sessions` is not sending a response

**Comment by ChrisLahaye** [comment]
Above issue was actually caused by koa-bodyparser, similarly for koa-body. The middleware converter koa-connect doesn't work for me, but express-to-koa did. As fix I now apply the bodyParser not to the App instance but to the route only where it is needed.

**Comment by alexstrat** [comment]
After upgrading to Node 12, I figured out [express-to-koa](https://github.com/kaelzhang/express-to-koa) was working better for me.
