### ISSUE TITLE
express route is not recognized

### ISSUE THREAD

**Issue by 1Sonia** [ForestAdmin/forest-express-mongoose#95]
Hi,

I used the mongodb "simple" example to create an Express app for Forest.
But as I created a route to a new Smart Action, my Express app sends a 404 code every time I try to call this Smart Action.

Can you confirm I just need to add this line to a file inside the route folder ?

```router.post('/forest/actions/add-client', liana.ensureAuthenticated, addClient)```

**Comment by arnaudbesnier** [comment]
Hi @1Sonia, can you display a log of your express app when the action is triggered?
I mean, does Forest hit the right route (`/forest/actions/add-client`)?

**Comment by 1Sonia** [comment]
Here is an extract of the log :
```POST /forest/actions/add-client 404 6.499 ms - 39```
It does hit the right route but finds no endpoint.

**Comment by 1Sonia** [comment]
I get a 500 status code, 

```POST /forest/actions/add-client 500 32.370 ms - 3632``` 
``` ReferenceError: log is not defined``` 
   ``` at addClient (/home/utilisateur/ForestTest/forest-examples/examples/mongodb-database/simple/routes/client.js:21:15) ... ```

**Comment by arnaudbesnier** [comment]
The error is now in the middleware "addClient", so the error is on your side. You're the owner of the business implementation.
